root: true

extends:
  - pegasus
  - pegasus/node

overrides:
  - files:
      - 'test/fixtures/ts/*.ts'
    extends:
      - pegasus/typescript-strict
    parserOptions:
      project: tsconfig.json
      tsconfigRootDir: test/fixtures/ts

  - files:
      - 'test/fixtures/jsx/*.jsx'
    extends:
      - pegasus/react
