root: true

extends:
  - pegasus
  - pegasus/node

overrides:
  - files:
      - 'test/fixtures/ts/*.ts'
    extends:
      - pegasus/typescript
    parserOptions:
      project: tsconfig.json
      tsconfigRootDir: test/fixtures/ts
